name: mangxahoi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  provider: ^6.1.5
  firebase_app_check: ^0.4.1+2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  intl: ^0.19.0
  image_picker: ^1.1.2  
  video_player: ^2.8.6
  cached_network_image: ^3.3.1
  visibility_detector: ^0.4.0+2
  flutter_image_compress: ^2.3.0
  timeago: ^3.6.0
  smooth_page_indicator: ^1.1.0
  path: ^1.9.0 
  zego_express_engine: ^3.0.0
  permission_handler: ^12.0.1
  uuid: ^4.2.1              # Dùng để tạo ID cuộc gọi duy nhất
  audioplayers: ^6.0.0
  flutter_reaction_button: ^2.0.1+1
  lottie: ^3.1.2
  file_picker: ^10.3.3       
  just_audio: ^0.9.38       
  percent_indicator: ^4.2.3
  qr_flutter: ^4.1.0  # Tạo QR code
  mobile_scanner: ^3.5.5  # Quét QR code
  share_plus: ^7.2.1  # Để chia sẻ QR code
  google_sign_in: ^6.2.1
  rxdart: ^0.28.0
  google_mlkit_smart_reply: ^0.11.0
  google_generative_ai: ^0.4.0
  firebase_messaging: ^16.0.0  # Đã dùng
  flutter_local_notifications: ^19.0.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  fake_cloud_firestore: 4.0.0
  camera: ^0.10.5
  google_mlkit_face_detection: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logoapp.png
    - assets/logosybau.png
    - assets/sounds/
    - assets/sounds/commingcall.mp3
    - assets/sounds/endcall.mp3
    - assets/reactions/
    - assets/reactions/angry.png
    - assets/icon/
    

# ⚙️ Cấu hình icon ứng dụng
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/logoapp.png"
  
  min_sdk_android: 21

# ⚙️ Cấu hình màn hình khởi động (Splash)
flutter_native_splash:
  color: "#ffffff"                 # Màu nền (trắng)
  image: assets/logosybau.png      # Ảnh hiển thị khi khởi động app
  android_12:
    image: assets/logosybau.png
    icon_background_color: "#ffffff"
  android: true
  ios: true
  web: true
